name: cfi-emb-pred
channels:
  - conda-forge
dependencies:
  - python=3.11
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - scikit-image
  - pip:
    - python-dotenv
    - mkdocs
    - -e .